config/routes.rb
ARLInventory::Application.routes.draw do
  resources :appointments
  resources :patients
  resources :physicians
  resources :hand_reciept_details
  resources :kits
  resources :budgets
  resources :component_models
  resources :hand_reciepts

  match '/users', :to => 'users#index', :as => "all_users", :via => "get"
  resources :groups

  resources :brands

  resources :categories

  resource :dashboard, :only => [:show]
  resources :roles_users
  resources :roles
  resources :inventory_records
  resources :locations
  resources :inventory_statuses
  resources :inventories
  get "home/index"

  devise_for :users

  root :to => 'home#index'

  match '*path(.:format)', :to => 'application#routing_error'
end

app/models/kit.rb
class Kit < ActiveRecord::Base
  
  belongs_to :location
  belongs_to :budget

  attr_accessible :location_id, :budget_id, :checkoutable, :cost, :insured, :tombstoned

  validates :budget, :presence => true
  validates :location, :presence => true
  validates :cost, :presence => true,
  					:numericality => true,
  					:format => {:with => /^\d{1,9}(\.\d{0,2})?$/, :message => "Numeric only"}


  
end

app/controllers/kits_controller.rb
class KitsController < ApplicationController
  # GET /kits
  # GET /kits.json
  def index
    @kits = Kit.all
    
    # using draper decorator
    # @kits = KitDecorator.decorate_collection(Kit.all)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kits }
    end
  end

  # GET /kits/1
  # GET /kits/1.json
  def show
    @kit = KitDecorator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kit }
    end
  end

  # GET /kits/new
  # GET /kits/new.json
  def new
    @kit = Kit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kit }
    end
  end

  # GET /kits/1/edit
  def edit
    @kit = Kit.find(params[:id])
  end

  # POST /kits
  # POST /kits.json
  def create
    # raise params[:kit].inspect
    @kit = Kit.new(params[:kit])

    respond_to do |format|
      if @kit.save
        format.html { redirect_to @kit, notice: 'Kit was successfully created.' }
        format.json { render json: @kit, status: :created, location: @kit }
      else
        format.html { render action: "new" }
        format.json { render json: @kit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kits/1
  # PUT /kits/1.json
  def update
    @kit = Kit.find(params[:id])

    respond_to do |format|
      if @kit.update_attributes(params[:kit])
        format.html { redirect_to @kit, notice: 'Kit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kits/1
  # DELETE /kits/1.json
  def destroy
    @kit = Kit.find(params[:id])
    @kit.destroy

    respond_to do |format|
      format.html { redirect_to kits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/kits_helper.rb
module KitsHelper
end

app/views/kits/_form.html.erb
<%= simple_form_for(@kit , :html => {:class => 'form-horizontal'}) do |f| %>
  <% if @kit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kit.errors.count, "error") %> prohibited this kit from being saved:</h2>

      <ul>
      <% @kit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :location , :class => 'control-label' %>
    <div class="controls">
    <%= f.association :location, :label => false, :prompt => 'Select location',:class  => 'text_field'  %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :budget , :class => 'control-label' %>
    <div class="controls">
    <%= f.association  :budget , :label => false, :prompt => 'Select Budget', :class => 'text_field'%>
    
    </div>
  </div>
  <div class="control-group">
    <%= f.label :tombstoned , :class => 'control-label' %>
    <div class="controls">
    <%= f.check_box :tombstoned , :class => 'text_field'%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :checkoutable , :class => 'control-label' %>
    <div class="controls">
    <%= f.check_box :checkoutable , :class => 'text_field'%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cost , :class => 'control-label' %>
    <div class="controls">
    <%= f.text_field :cost , :class => 'text_field'%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :insured , :class => 'control-label' %>
    <div class="controls">
    <%= f.check_box :insured , :class => 'text_field'%>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/kits/edit.html.erb
<div class="root">
    <div class="row">
        <div class="span12">
            <div class="grey-box">  
			<h3>Editing kit</h3>

			<%= render 'form' %>

			<%= link_to 'Show', @kit %> |
			<%= link_to 'Back', kits_path %>
            </div>      
        </div>
    </div>
</div>

app/views/kits/index.html.erb
<div class="root">
    <div class="row">
        <div class="span12">
            <div class="grey-box">  
                <h3>Listing kits</h3>

                <table class="table table-striped">
                  <tr>
                    <th>Location</th>
                    <th>Budget</th>
                    <th>Tombstoned</th>
                    <th>Checkoutable</th>
                    <th>Cost</th>
                    <th>Insured</th>
                    <th></th>
                    <th></th>
                    <th></th>
                  </tr>

                <% @kits.each do |kit| %>
                  <tr>
                    <td><%= kit.location.name %></td>
                    <td><%= kit.budget.name %></td>
                    <td><%= kit.tombstoned %></td>
                    <td><%= kit.checkoutable %></td>
                    <td><%= number_to_currency(kit.cost) %></td>
                    <td><%= to_yes_no(kit.insured) %></td>
                    <td><%= link_to 'Show', kit %></td>
                    <td><%= link_to 'Edit', edit_kit_path(kit) %></td>
                    <td><%= link_to 'Destroy', kit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
                </table>

                <br />

                <%= link_to 'New Kit', new_kit_path %>
            </div>      
        </div>
    </div>
</div>

app/views/kits/new.html.erb
<div class="root">
    <div class="row">
        <div class="span12">
            <div class="grey-box">  
				<h3>New kit</h3>

				<%= render 'form' %>

				<%= link_to 'Back', kits_path %>
            </div>      
        </div>
    </div>
</div>

app/views/kits/show.html.erb
<div class="root">
    <div class="row">
        <div class="span12">
            <div class="grey-box">  
              <p id="notice"><%= notice %></p>

              <p>
                <b>Location:</b>
                <%= @kit.location.name %>
              </p>

              <p>
                <b>Budget:</b>
                <%= @kit.budget.name %>
              </p>

              <p>
                <b>Tombstoned:</b>
                <%= @kit.tombstoned %>
              </p>

              <p>
                <b>Checkoutable:</b>
                <%= @kit.checkoutable %>
              </p>

              <p>
                <b>Cost:</b>
                <%= number_to_currency(@kit.cost) %>
              </p>

              <p>
                <b>Insured:</b>
                <%= to_yes_no(@kit.insured) %>
              </p>


              <%= link_to 'Edit', edit_kit_path(@kit) %> |
              <%= link_to 'Back', kits_path %>
            </div>      
        </div>
    </div>
</div>